import ClientOnly from '@/components/ClientOnly'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Search from '@/components/navbar/Search'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>       
        <ClientOnly>
           <Navbar /> 
           <Search/>
          {children}
        </ClientOnly>
       
      </body>
    </html>
  )
}
